config/routes.rb
Rails.application.routes.draw do
  resources :student_marks
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :colleges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
    before_create :name
    before_update :name
    has_one :student_mark

    mount_uploader :avatar, AvatarUploader

    def name
        self.name = self.first_name + " " + self.last_name
    end
end

app/models/student_mark.rb
class StudentMark < ApplicationRecord
  belongs_to :student
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
    def index
        @colleges = College.all
    end

    def show
        @college = College.find(params[:id])
    end

    def new
        @college = College.new
    end

    def create
        @college = College.new(college_params)

        if @college.save
            redirect_to colleges_path            
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @college = College.find(params[:id])
    end

    def update
        @college = College.find(params[:id])

        if @college.update(college_params)
          redirect_to @college
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @college = College.find(params[:id])
        @college.destroy

        redirect_to colleges_path, status: :see_other
    end    

    private
        def college_params
            params.require(:college).permit(:name, :city, :state)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/student_marks_controller.rb
class StudentMarksController < ApplicationController
  before_action :set_student_mark, only: %i[ show edit update destroy ]

  # GET /student_marks or /student_marks.json
  def index
    @student_marks = StudentMark.all
  end

  # GET /student_marks/1 or /student_marks/1.json
  def show
  end

  # GET /student_marks/new
  def new
    @student_mark = StudentMark.new
  end

  # GET /student_marks/1/edit
  def edit
  end

  # POST /student_marks or /student_marks.json
  def create
    @student_mark = StudentMark.new(student_mark_params)

    respond_to do |format|
      if @student_mark.save
        StudentMailer.student_mark_email(@student_mark).deliver_now
        format.html { redirect_to student_mark_url(@student_mark), notice: "Student mark was successfully created." }
        format.json { render :show, status: :created, location: @student_mark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_marks/1 or /student_marks/1.json
  def update
    respond_to do |format|
      if @student_mark.update(student_mark_params)
        format.html { redirect_to student_mark_url(@student_mark), notice: "Student mark was successfully updated." }
        format.json { render :show, status: :ok, location: @student_mark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_marks/1 or /student_marks/1.json
  def destroy
    @student_mark.destroy

    respond_to do |format|
      format.html { redirect_to student_marks_url, notice: "Student mark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_mark
      @student_mark = StudentMark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_mark_params
      params.require(:student_mark).permit(:m1, :m2, :m3, :total, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :age, :email, :course, :address, :mobile, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/student_marks_helper.rb
module StudentMarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/colleges/_form.html.erb
<%= form_with model: @college do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @college.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
    <% @college.errors.full_messages_for(:city).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :state %><br>
    <%= form.text_field :state %>
    <% @college.errors.full_messages_for(:state).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Edit College</h1>

<%= render "form", college: @college %>

app/views/colleges/index.html.erb
<h1>College List</h1>
<ul>
    <% @colleges.each do |college| %>
        <li>
            <%= link_to college.name, college%>
        </li>
    <% end%>
</ul>

<%= link_to "New College", new_college_path%>

app/views/colleges/new.html.erb
<h1>New College</h1>
<%= render "form", college: @college %>

app/views/colleges/show.html.erb
<h1><%= @college.name %></h1>

<p><%= @college.city %></p>
<p><%= @college.state %></p>

<ul>
  <li><%= link_to "Edit", edit_college_path(@college) %></li>
  <li><%= button_to "Destroy", college_path(@college),method: :delete, data: {confirm: "Are you sure?"}  %></li>
</ul>

app/views/home/index.html.erb
<h1>Welcome Rails</h1>

app/views/layouts/_header.html.erb
<div class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="float-left">
                    <div class="hamburger sidebar-toggle">
                        <span class="line"></span>
                        <span class="line"></span>
                        <span class="line"></span>
                    </div>
                </div>
                <div class="float-right">
                    <div class="dropdown dib">
                        <div class="header-icon" data-toggle="dropdown">
                            <i class="ti-bell"></i>
                            <div class="drop-down dropdown-menu dropdown-menu-right">
                                <div class="dropdown-content-heading">
                                    <span class="text-left">Recent Notifications</span>
                                </div>
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/3.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Mr. John</div>
                                                    <div class="notification-text">5 members joined today </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/3.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Mariam</div>
                                                    <div class="notification-text">likes a photo of you</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/3.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Tasnim</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/3.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Mr. John</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="text-center">
                                            <a href="#" class="more-link">See All</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown dib">
                        <div class="header-icon" data-toggle="dropdown">
                            <i class="ti-email"></i>
                            <div class="drop-down dropdown-menu dropdown-menu-right">
                                <div class="dropdown-content-heading">
                                    <span class="text-left">2 New Messages</span>
                                    <a href="email.html">
                                        <i class="ti-pencil-alt pull-right"></i>
                                    </a>
                                </div>
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li class="notification-unread">
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/1.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Michael Qin</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="notification-unread">
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/2.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Mr. John</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/3.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Michael Qin</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <img class="pull-left m-r-10 avatar-img"
                                                    src="/assets/avatar/2.jpg" alt="" />
                                                <div class="notification-content">
                                                    <small class="notification-timestamp pull-right">02:34
                                                        PM</small>
                                                    <div class="notification-heading">Mr. John</div>
                                                    <div class="notification-text">Hi Teddy, Just wanted to let you
                                                        ...</div>
                                                </div>
                                            </a>
                                        </li>
                                        <li class="text-center">
                                            <a href="#" class="more-link">See All</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown dib">
                        <div class="header-icon" data-toggle="dropdown">
                            <span class="user-avatar">John
                                <i class="ti-angle-down f-s-10"></i>
                            </span>
                            <div class="drop-down dropdown-profile dropdown-menu dropdown-menu-right">
                                <div class="dropdown-content-heading">
                                    <span class="text-left">Upgrade Now</span>
                                    <p class="trial-day">30 Days Trail</p>
                                </div>
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="#">
                                                <i class="ti-user"></i>
                                                <span>Profile</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="#">
                                                <i class="ti-email"></i>
                                                <span>Inbox</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="ti-settings"></i>
                                                <span>Setting</span>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="#">
                                                <i class="ti-lock"></i>
                                                <span>Lock Screen</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="ti-power-off"></i>
                                                <span>Logout</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
    <div class="nano">
        <div class="nano-content">
            <ul>
                <div class="logo"><a href="index.html">
                    <!-- <img src="assets/images/logo.png" alt="" /> --><span>Focus</span></a>
                </div>
                <%# <%= link_to "Home", root_path%>
                <li><a href="/"><i class="ti-calendar"></i> Home </a></li>
                <li><a href="/colleges"><i class="ti-calendar"></i> College </a></li>
                <li><a href="/students"><i class="ti-calendar"></i> Students </a></li>
                <li><a href="/student_marks"><i class="ti-calendar"></i> Student Marks </a></li>
                <li><a><i class="ti-close"></i> Logout</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Focus Admin: Creative Admin Dashboard</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="/assets/lib/calendar2/pignose.calendar.min.css" rel="stylesheet">
    <link href="/assets/lib/chartist/chartist.min.css" rel="stylesheet">
    <link href="/assets/lib/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/lib/themify-icons.css" rel="stylesheet">
    <link href="/assets/lib/owl.carousel.min.css" rel="stylesheet" />
    <link href="/assets/lib/owl.theme.default.min.css" rel="stylesheet" />
    <link href="/assets/lib/weather-icons.css" rel="stylesheet" />
    <link href="/assets/lib/menubar/sidebar.css" rel="stylesheet">
    <link href="/assets/lib/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/lib/helper.css" rel="stylesheet">
    <link href="/assets/style.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/sidebar'%>
    <%= render 'layouts/header'%>
    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                
                <section id="main-content">
                  <%= yield %>
                </section>
            </div>
        </div>
    </div>
  </body>
</html>

app/views/student_marks/_form.html.erb
<div class="card">
    <div class="card-body">
        <div class="basic-form">
            <%= form_with(model: student_mark, local: true) do |form| %>
              <% if student_mark.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(student_mark.errors.count, "error") %> prohibited this student_mark from being saved:</h2>

                  <ul>
                    <% student_mark.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="form-group">
                  <%= form.label :m1 %>
                  <%= form.number_field :m1 %>
              </div>

              <div class="form-group">
                <%= form.label :m2 %>
                <%= form.number_field :m2 %>
              </div>

              <div class="form-group">
                <%= form.label :m3 %>
                <%= form.number_field :m3 %>
              </div>

              <div class="form-group">
                <%= form.label :total %>
                <%= form.number_field :total %>
              </div>

              <div class="form-group">
                <%= form.label :student_id %>
                <%= form.select :student_id, options_for_select(Student.all.map{|s|[s.first_name, s.id]}), {:class => 'form-control'} %>
              </div>

              <div class="actions">
                <%= form.submit %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/student_marks/edit.html.erb
<h1>Editing Student Mark</h1>

<%= render 'form', student_mark: @student_mark %>

<%= link_to 'Show', @student_mark %> |
<%= link_to 'Back', student_marks_path %>

app/views/student_marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Marks</h1>

<table>
  <thead>
    <tr>
      <th>M1</th>
      <th>M2</th>
      <th>M3</th>
      <th>Total</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_marks.each do |student_mark| %>
      <tr>
        <td><%= student_mark.m1 %></td>
        <td><%= student_mark.m2 %></td>
        <td><%= student_mark.m3 %></td>
        <td><%= student_mark.total %></td>
        <td><%= student_mark.student.name %></td>
        <td><%= link_to 'Show', student_mark %></td>
        <td><%= link_to 'Edit', edit_student_mark_path(student_mark) %></td>
        <td><%= link_to 'Destroy', student_mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Mark', new_student_mark_path %>

app/views/student_marks/new.html.erb
<h1>New Student Mark</h1>

<%= render 'form', student_mark: @student_mark %>

<%= link_to 'Back', student_marks_path %>

app/views/student_marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>M1:</strong>
  <%= @student_mark.m1 %>
</p>

<p>
  <strong>M2:</strong>
  <%= @student_mark.m2 %>
</p>

<p>
  <strong>M3:</strong>
  <%= @student_mark.m3 %>
</p>

<p>
  <strong>Total:</strong>
  <%= @student_mark.total %>
</p>

<p>
  <strong>Student:</strong>
  <%= @student_mark.student.name %>
</p>

<%= link_to 'Edit', edit_student_mark_path(@student_mark) %> |
<%= link_to 'Back', student_marks_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile %>
  </div>
  
  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, multiple: false %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Course</th>
      <th>Address</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.email %></td>
        <td><%= student.course %></td>
        <td><%= student.address %></td>
        <td><%= student.mobile %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>
<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<%= image_tag(@student.avatar.url, alt: 'Image') if @student.avatar? %>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>